// prisma/seed.js
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function seed ()
{
    const questionMappings = [
        { key: "firstName", question: "What is your first name?" },
        { key: "lastName", question: "What is your last name?" },
        { key: "email", question: "What is your email address?" },
        { key: "phone", question: "What is your phone number?" },
        { key: "address", question: "What is your street address?" },
        { key: "city", question: "In which city do you live?" },
        { key: "state", question: "What state or province do you reside in?" },
        { key: "zip", question: "What is your postal code?" },
        { key: "country", question: "Which country do you live in?" },
        { key: "company", question: "What is your company name?" },
        { key: "jobTitle", question: "What is your job title?" },
        { key: "website", question: "What is your website URL?" },
        { key: "message", question: "Please describe your message in detail." },
        { key: "comments", question: "Do you have any additional comments?" },
        { key: "feedback", question: "Please provide your feedback." },
        { key: "password", question: "Choose a secure password." },
        { key: "confirmPassword", question: "Confirm your chosen password." },
        { key: "dob", question: "What is your date of birth?" },
        { key: "gender", question: "What is your gender?" },
        { key: "maritalStatus", question: "What is your marital status?" },
        { key: "occupation", question: "What is your occupation?" },
        { key: "industry", question: "Which industry do you work in?" },
        { key: "experience", question: "How many years of experience do you have?" },
        { key: "education", question: "What is your highest level of education?" },
        { key: "degree", question: "What degree have you earned?" },
        { key: "school", question: "Which school or institution did you attend?" },
        { key: "graduationYear", question: "What year did you graduate?" },
        { key: "reference", question: "Please provide a reference if available." },
        { key: "commentsOptional", question: "Any optional comments?" },
        { key: "projectDescription", question: "Briefly describe your project." },
        { key: "budget", question: "What is your budget range?" },
        { key: "deadline", question: "What is your project deadline?" },
        { key: "requirements", question: "List your project requirements." },
        { key: "preferences", question: "What are your preferences?" },
        { key: "timeZone", question: "What is your time zone?" },
        { key: "language", question: "What is your preferred language?" },
        { key: "skills", question: "List your relevant skills." },
        { key: "interests", question: "What are your interests?" },
        { key: "hobbies", question: "What are your hobbies?" },
        { key: "bio", question: "Write a short bio about yourself." },
        { key: "summary", question: "Provide a brief summary of your background." },
        { key: "purpose", question: "What is the purpose of this form?" },
        { key: "question1", question: "Please answer question 1." },
        { key: "question2", question: "Please answer question 2." },
        { key: "question3", question: "Please answer question 3." },
        { key: "question4", question: "Please answer question 4." },
        { key: "question5", question: "Please answer question 5." },
        { key: "referenceCode", question: "Enter your reference code, if available." },
        { key: "promoCode", question: "Enter your promotional code." },
        { key: "discount", question: "What discount are you applying for?" },
        { key: "subscriptionPlan", question: "Choose your subscription plan." },
        { key: "paymentMethod", question: "Select your payment method." },
        { key: "cardNumber", question: "Enter your card number." },
        { key: "expiryDate", question: "What is your card's expiry date?" },
        { key: "cvv", question: "Enter your card's CVV." },
        { key: "billingAddress", question: "What is your billing address?" },
        { key: "shippingAddress", question: "What is your shipping address?" },
        { key: "deliveryInstructions", question: "Any special delivery instructions?" },
        { key: "orderNumber", question: "Enter your order number." },
        { key: "trackingNumber", question: "Enter your tracking number." },
        { key: "feedbackRating", question: "Rate your experience (1-5)." },
        { key: "serviceQuality", question: "How would you rate our service quality?" },
        { key: "satisfaction", question: "How satisfied are you with our service?" },
        { key: "improvementSuggestions", question: "Any suggestions for improvement?" },
        { key: "contactReason", question: "What is the reason for contacting us?" },
        { key: "appointmentDate", question: "Select your appointment date." },
        { key: "appointmentTime", question: "Select your appointment time." },
        { key: "consultationType", question: "What type of consultation do you need?" },
        { key: "preferredContactMethod", question: "What is your preferred method of contact?" },
        { key: "emergencyContact", question: "Enter your emergency contact details." },
        { key: "relationship", question: "What is your relationship with the emergency contact?" },
        { key: "medicalHistory", question: "Provide your relevant medical history." },
        { key: "allergies", question: "List any allergies you have." },
        { key: "medications", question: "List your current medications." },
        { key: "symptoms", question: "Describe your symptoms." },
        { key: "insuranceProvider", question: "Who is your insurance provider?" },
        { key: "policyNumber", question: "Enter your insurance policy number." },
        { key: "claimNumber", question: "Enter your claim number (if applicable)." },
        { key: "preferredDoctor", question: "Who is your preferred doctor?" },
        { key: "referralSource", question: "How did you hear about us?" },
        { key: "appointmentType", question: "Select the type of appointment you need." },
        { key: "meetingLocation", question: "Where will the meeting take place?" },
        { key: "roomPreference", question: "Do you have a room preference?" },
        { key: "equipmentNeeded", question: "List any equipment you require." },
        { key: "setupDetails", question: "Provide details about the setup." },
        { key: "travelDistance", question: "What is your expected travel distance?" },
        { key: "pickupTime", question: "Select your pickup time." },
        { key: "dropoffTime", question: "Select your dropoff time." },
        { key: "deliveryDate", question: "Select your delivery date." },
        { key: "deliveryTime", question: "Select your delivery time." },
        { key: "projectBudget", question: "What is your project budget?" },
        { key: "projectTimeline", question: "What is your project timeline?" },
        { key: "designPreferences", question: "Describe your design preferences." },
        { key: "colorScheme", question: "What color scheme do you prefer?" },
        { key: "logoDetails", question: "Provide details for your logo design." },
        { key: "marketingGoals", question: "What are your marketing goals?" },
        { key: "targetAudience", question: "Who is your target audience?" },
        { key: "socialMedia", question: "List your social media handles." },
        { key: "campaignBudget", question: "What is your campaign budget?" },
        { key: "campaignObjective", question: "What is your campaign objective?" },
        { key: "preferredContactTime", question: "What is your preferred time to be contacted?" },
        { key: "communicationMethod", question: "Which communication method do you prefer (phone, email, text)?" },
        { key: "alternateEmail", question: "Please provide an alternate email address, if any." },
        { key: "emergencyPhone", question: "What is your emergency contact phone number?" },
        { key: "residentialAddress", question: "What is your full residential address?" },
        { key: "cityOfResidence", question: "Which city do you reside in?" },
        { key: "stateOfResidence", question: "What is your state or province of residence?" },
        { key: "postalCode", question: "What is your postal or ZIP code?" },
        { key: "countryOfResidence", question: "Which country do you live in?" },
        { key: "workAddress", question: "What is your work address?" },
        { key: "positionTitle", question: "What is your position or title at work?" },
        { key: "department", question: "Which department do you work in?" },
        { key: "workPhone", question: "What is your work phone number?" },
        { key: "linkedinProfile", question: "Please provide your LinkedIn profile URL." },
        { key: "twitterHandle", question: "What is your Twitter handle?" },
        { key: "instagramUsername", question: "What is your Instagram username?" },
        { key: "facebookProfile", question: "Please share your Facebook profile URL." },
        { key: "githubUsername", question: "What is your GitHub username?" },
        { key: "portfolioUrl", question: "What is the URL of your portfolio or website?" },
        { key: "preferredLanguage", question: "What is your preferred language?" },
        { key: "highestQualification", question: "What is your highest qualification?" },
        { key: "fieldOfStudy", question: "What was your field of study?" },
        { key: "graduationInstitution", question: "Which institution did you graduate from?" },
        { key: "yearOfGraduation", question: "What year did you graduate?" },
        { key: "certifications", question: "List any certifications you have obtained." },
        { key: "skillsList", question: "What are your key skills?" },
        { key: "hobbiesList", question: "What are your hobbies or interests?" },
        { key: "availableForWork", question: "Are you available for work opportunities?" },
        { key: "currentEmployer", question: "Who is your current employer?" },
        { key: "yearsOfExperience", question: "How many years of work experience do you have?" },
        { key: "industryExperience", question: "Which industry do you have experience in?" },
        { key: "projectDetails", question: "Please describe your project details." },
        { key: "projectBudget", question: "What is your project budget?" },
        { key: "projectDeadline", question: "When is your project deadline?" },
        { key: "projectGoals", question: "What are your project goals?" },
        { key: "expectedOutcomes", question: "What outcomes do you expect from this project?" },
        { key: "teamSize", question: "What is the size of your team?" },
        { key: "roleInTeam", question: "What is your role within the team?" },
        { key: "clientFeedback", question: "What feedback have you received from clients?" },
        { key: "marketingStrategy", question: "What is your current marketing strategy?" },
        { key: "socialMediaUsage", question: "Which social media platforms do you use regularly?" },
        { key: "contentPreferences", question: "What type of content do you prefer to see?" },
        { key: "newsletterSubscription", question: "Would you like to subscribe to our newsletter?" },
        { key: "serviceInterest", question: "Which service are you most interested in?" },
        { key: "productFeedback", question: "Please provide feedback on our product." },
        { key: "customerSatisfaction", question: "How satisfied are you with our service?" },
        { key: "improvementSuggestions", question: "What suggestions do you have for improvement?" },
        { key: "contactReason", question: "What is the reason for contacting us?" },
        { key: "appointmentDate", question: "Select your appointment date." },
        { key: "appointmentTime", question: "Select your appointment time." },
        { key: "consultationType", question: "What type of consultation do you need?" },
        { key: "preferredContactMethod", question: "What is your preferred method of contact?" },
        { key: "emergencyContact", question: "Enter your emergency contact details." },
        { key: "relationship", question: "What is your relationship with your emergency contact?" },
        { key: "medicalHistory", question: "Provide your relevant medical history." },
        { key: "allergies", question: "List any allergies you have." },
        { key: "medications", question: "List your current medications." },
        { key: "symptoms", question: "Describe your symptoms." },
        { key: "insuranceProvider", question: "Who is your insurance provider?" },
        { key: "policyNumber", question: "Enter your insurance policy number." },
        { key: "claimNumber", question: "Enter your claim number (if applicable)." },
        { key: "preferredDoctor", question: "Who is your preferred doctor?" },
        { key: "referralSource", question: "How did you hear about us?" },
        { key: "appointmentType", question: "Select the type of appointment you need." },
        { key: "meetingLocation", question: "Where will the meeting take place?" },
        { key: "roomPreference", question: "Do you have a room preference?" },
        { key: "equipmentNeeded", question: "List any equipment you require." },
        { key: "setupDetails", question: "Provide details about the setup." },
        { key: "travelDistance", question: "What is your expected travel distance?" },
        { key: "pickupTime", question: "Select your pickup time." },
        { key: "dropoffTime", question: "Select your dropoff time." },
        { key: "deliveryDate", question: "Select your delivery date." },
        { key: "deliveryTime", question: "Select your delivery time." },
        { key: "designBudget", question: "What is your design budget?" },
        { key: "projectTimeline", question: "What is your project timeline?" },
        { key: "designPreferences", question: "Describe your design preferences." },
        { key: "colorScheme", question: "What color scheme do you prefer?" },
        { key: "logoDetails", question: "Provide details for your logo design." },
        { key: "marketingGoals", question: "What are your marketing goals?" },
        { key: "targetAudience", question: "Who is your target audience?" },
        { key: "socialMedia", question: "List your social media handles." },
        { key: "campaignBudget", question: "What is your campaign budget?" },
        { key: "campaignObjective", question: "What is your campaign objective?" },
        { key: "productLaunchDate", question: "When is your product launch date?" },
        { key: "productVersion", question: "What is the version of your product?" },
        { key: "technicalSupport", question: "Do you require technical support?" },
        { key: "maintenancePlan", question: "What is your preferred maintenance plan?" },
        { key: "warrantyPeriod", question: "What is the warranty period for your product?" },
        { key: "returnPolicy", question: "What is your return policy?" },
        { key: "shippingMethod", question: "What shipping method do you prefer?" },
        { key: "orderNumber", question: "Enter your order number." },
        { key: "trackingNumber", question: "Enter your tracking number." },
        { key: "customerLoyalty", question: "Are you enrolled in our customer loyalty program?" },
        { key: "referralProgram", question: "Are you interested in our referral program?" },
        { key: "satisfactionRating", question: "What is your satisfaction rating (1-5)?" },
        { key: "reviewComments", question: "Please leave any review comments you have." },
        { key: "demoRequest", question: "Would you like to request a demo?" },
        { key: "freeTrialRequest", question: "Would you like to request a free trial?" },
        { key: "appointmentReason", question: "What is the reason for your appointment?" },
        { key: "additionalNotes", question: "Any additional notes or information?" },
        { key: "nickname", question: "What is your nickname?" },
        { key: "middleName", question: "What is your middle name?" },
        { key: "maidenName", question: "What is your mother's maiden name?" },
        { key: "preferredPronouns", question: "What are your preferred pronouns?" },
        { key: "ethnicity", question: "What is your ethnicity?" },
        { key: "religion", question: "What is your religion?" },
        { key: "politicalViews", question: "What are your political views?" },
        { key: "favoriteHobby", question: "What is your favorite hobby?" },
        { key: "favoriteBook", question: "What is your favorite book?" },
        { key: "favoriteMovie", question: "What is your favorite movie?" },
        { key: "favoriteMusicGenre", question: "What is your favorite music genre?" },
        { key: "favoriteBand", question: "Who is your favorite band?" },
        { key: "favoriteSportsTeam", question: "What is your favorite sports team?" },
        { key: "favoriteSport", question: "What sport do you enjoy watching the most?" },
        { key: "travelFrequency", question: "How often do you travel?" },
        { key: "favoriteTravelDestination", question: "What is your favorite travel destination?" },
        { key: "vacationType", question: "Do you prefer beach, mountain, or city vacations?" },
        { key: "dietaryPreferences", question: "Do you have any dietary preferences or restrictions?" },
        { key: "allergyInfo", question: "Do you have any food allergies?" },
        { key: "exerciseRoutine", question: "What does your exercise routine look like?" },
        { key: "healthGoals", question: "What are your current health goals?" },
        { key: "smokingStatus", question: "Do you smoke?" },
        { key: "alcoholConsumption", question: "How often do you consume alcohol?" },
        { key: "sleepHours", question: "How many hours do you sleep on average?" },
        { key: "stressLevel", question: "How would you rate your stress level?" },
        { key: "dailyWaterIntake", question: "How many glasses of water do you drink daily?" },
        { key: "caffeineIntake", question: "How much caffeine do you consume per day?" },
        { key: "meditationPractice", question: "Do you practice meditation regularly?" },
        { key: "favoriteCuisine", question: "What is your favorite type of cuisine?" },
        { key: "cookingSkill", question: "How would you rate y our cooking skills?" },
        { key: "mealPreference", question: "Do you prefer home-cooked meals or dining out?" },
        { key: "shoppingHabits", question: "How often do you shop online?" },
        { key: "fashionStyle", question: "How would you describe your fashion style?" },
        { key: "personalBudget", question: "What is your monthly personal budget?" },
        { key: "savingsGoal", question: "What is your savings goal for this year?" },
        { key: "investmentExperience", question: "What is your experience with investing?" },
        { key: "riskTolerance", question: "How would you describe your risk tolerance?" },
        { key: "creditScore", question: "What is your current credit score?" },
        { key: "loanInterest", question: "What is your current loan interest rate?" },
        { key: "mortgageStatus", question: "Do you currently have a mortgage?" },
        { key: "rentalStatus", question: "Are you a renter or a homeowner?" },
        { key: "insuranceCoverage", question: "What types of insurance do you currently have?" },
        { key: "retirementPlan", question: "Do you have a retirement plan in place?" },
        { key: "emergencyFund", question: "Have you set up an emergency fund?" },
        { key: "investmentPortfolio", question: "How would you describe your investment portfolio?" },
        { key: "financialAdvisor", question: "Do you work with a financial advisor?" },
        { key: "spendingHabits", question: "How would you describe your spending habits?" },
        { key: "budgetingTool", question: "Do you use any budgeting tools?" },
        { key: "creditCardUsage", question: "How many credit cards do you have?" },
        { key: "debtLevel", question: "What is your current debt level?" },
        { key: "carOwnership", question: "Do you own a car?" },
        { key: "vehicleType", question: "What type of vehicle do you own?" },
        { key: "fuelEfficiency", question: "What is your vehicle's fuel efficiency?" },
        { key: "publicTransportUsage", question: "How often do you use public transportation?" },
        { key: "commuteTime", question: "What is your average commute time?" },
        { key: "workFromHome", question: "Do you work from home?" },
        { key: "officeCommute", question: "How do you commute to your office?" },
        { key: "parkingAvailability", question: "Is parking available at your workplace?" },
        { key: "gymMembership", question: "Do you have a gym membership?" },
        { key: "favoriteWorkout", question: "What is your favorite workout routine?" },
        { key: "healthSupplements", question: "Do you take any health supplements?" },
        { key: "dietType", question: "Are you vegetarian, vegan, or follow another diet?" },
        { key: "mealFrequency", question: "How many meals do you eat per day?" },
        { key: "snackingHabit", question: "Do you snack frequently?" },
        { key: "cookingFrequency", question: "How often do you cook at home?" },
        { key: "foodBudget", question: "What is your monthly food budget?" },
        { key: "travelPreferences", question: "What are your travel preferences?" },
        { key: "accommodationPreference", question: "Do you prefer hotels, hostels, or vacation rentals?" },
        { key: "vacationBudget", question: "What is your typical vacation budget?" },
        { key: "travelCompanions", question: "Do you usually travel alone or with others?" },
        { key: "preferredAirline", question: "Do you have a preferred airline?" },
        { key: "frequentFlyer", question: "Are you a frequent flyer?" },
        { key: "visaRequirements", question: "Do you require visa assistance?" },
        { key: "travelInsurance", question: "Do you purchase travel insurance?" },
        { key: "languageProficiency", question: "Which languages are you proficient in?" },
        { key: "foreignTravelExperience", question: "How often do you travel internationally?" },
        { key: "culturalInterests", question: "What cultural activities interest you?" },
        { key: "artInterests", question: "What type of art do you appreciate?" },
        { key: "musicInterests", question: "What kind of music do you enjoy?" },
        { key: "sportsParticipation", question: "Do you actively participate in any sports?" },
        { key: "outdoorActivities", question: "What outdoor activities do you enjoy?" },
        { key: "techSavviness", question: "How would you rate your tech savviness?" },
        { key: "appUsage", question: "Which mobile apps do you use daily?" },
        { key: "socialNetworking", question: "How active are you on social networking sites?" },
        { key: "onlineShopping", question: "How often do you shop online?" },
        { key: "streamingServices", question: "Which streaming services do you subscribe to?" },
        { key: "gamingInterest", question: "Are you interested in video games?" },
        { key: "pcGaming", question: "Do you play PC games?" },
        { key: "consoleGaming", question: "Do you play console games?" },
        { key: "mobileGaming", question: "Do you play mobile games?" },
        { key: "favoriteGameGenre", question: "What is your favorite game genre?" },
        { key: "eSportsInterest", question: "Are you interested in eSports?" },
        { key: "learningStyle", question: "What is your preferred learning style?" },
        { key: "onlineCourses", question: "Do you take online courses?" },
        { key: "educationalPlatform", question: "Which educational platforms do you use?" },
        { key: "certificationGoals", question: "Are you pursuing any certifications?" },
        { key: "careerGoals", question: "What are your career goals?" },
        { key: "professionalDevelopment", question: "How do you pursue professional development?" },
        { key: "networkingEvents", question: "Do you attend networking events?" },
        { key: "mentorship", question: "Are you interested in mentorship opportunities?" },
        { key: "industryConferences", question: "Do you attend industry conferences?" },
        { key: "businessPublications", question: "Which business publications do you read?" },
        { key: "investmentInterests", question: "What types of investments interest you?" },
        { key: "savingsStrategy", question: "What is your savings strategy?" },
        { key: "financialPlanning", question: "How do you plan your finances?" },
        { key: "retirementSavings", question: "How much do you save for retirement monthly?" },
        { key: "realEstateInvesting", question: "Are you interested in real estate investing?" },
        { key: "stockInvesting", question: "Do you invest in stocks?" },
        { key: "bondInvesting", question: "Do you invest in bonds?" },
        { key: "cryptocurrencyInterest", question: "Are you interested in cryptocurrencies?" },
        { key: "riskManagementStrategy", question: "What is your risk management strategy?" },
        { key: "budgetingExperience", question: "How experienced are you with budgeting?" },
        { key: "debtManagement", question: "How do you manage your debts?" },
        { key: "creditManagement", question: "How do you manage your credit?" },
        { key: "financialGoalsShortTerm", question: "What are your short-term financial goals?" },
        { key: "financialGoalsLongTerm", question: "What are your long-term financial goals?" },
        { key: "investmentTimeHorizon", question: "What is your investment time horizon?" },
        { key: "taxPlanning", question: "How do you plan for taxes?" },
        { key: "estatePlanning", question: "Do you have an estate plan?" },
        { key: "charityDonations", question: "Do you make regular charity donations?" },
        { key: "volunteerWork", question: "Do you participate in volunteer work?" },
        { key: "environmentalValues", question: "How important are environmental values to you?" },
        { key: "politicalEngagement", question: "How engaged are you politically?" },
        { key: "communityService", question: "Do you participate in community service?" },
        { key: "personalBrand", question: "How do you promote your personal brand?" },
        { key: "socialMediaStrategy", question: "What is your social media strategy?" },
        { key: "blogging", question: "Do you maintain a blog?" },
        { key: "podcasting", question: "Are you interested in podcasting?" },
        { key: "videoContent", question: "Do you create video content?" },
        { key: "onlinePresenceStrength", question: "How strong is your online presence?" },
        { key: "digitalFootprint", question: "What is your digital footprint like?" },
        { key: "cyberSecurityAwareness", question: "How aware are you of cyber security practices?" },
        { key: "privacyConcerns", question: "How concerned are you about online privacy?" },
        { key: "dataUsage", question: "How do you manage your data usage?" },
        { key: "technologyAdoption", question: "How quickly do you adopt new technology?" },
        { key: "appUsageFrequency", question: "How frequently do you use mobile apps?" },
        { key: "internetSpeed", question: "What is your average internet speed?" },
        { key: "deviceUsage", question: "What devices do you use regularly?" },
        { key: "wearableTech", question: "Do you use any wearable technology?" },
        { key: "smartHomeDevices", question: "Do you use smart home devices?" },
        { key: "onlineShoppingPreference", question: "What is your online shopping preference?" },
        { key: "ecommerceExperience", question: "Describe your eCommerce experience." },
        { key: "mobilePaymentUsage", question: "Do you use mobile payment systems?" },
        { key: "contactlessPayments", question: "How often do you use contactless payments?" },
        { key: "bankingAppUsage", question: "Do you use a mobile banking app?" },
        { key: "investmentAppUsage", question: "Do you use investment apps?" },
        { key: "cryptoTrading", question: "Do you trade cryptocurrencies?" },
        { key: "financialNewsSources", question: "What are your preferred financial news sources?" },
        { key: "spendingTracker", question: "Do you use a spending tracker?" },
        { key: "creditMonitoring", question: "Do you monitor your credit score?" },
        { key: "customerOnboardingSatisfaction", question: "How satisfied are you with your customer onboarding process?" },
        { key: "afterSaleServiceRating", question: "How would you rate our after-sale service?" },
        { key: "warrantyClaimFrequency", question: "How frequently do you file warranty claims?" },
        { key: "userInterfaceResponsiveness", question: "How responsive do you find our user interface?" },
        { key: "mobileAppPerformance", question: "How is the performance of our mobile app?" },
        { key: "serverScalability", question: "How scalable do you find our server infrastructure?" },
        { key: "dataBackupFrequency", question: "How often do you perform data backups?" },
        { key: "disasterRecoveryPlan", question: "Do you have a disaster recovery plan in place?" },
        { key: "employeeTurnoverCost", question: "What is the cost associated with employee turnover?" },
        { key: "trainingEffectiveness", question: "How effective are your employee training programs?" },
        { key: "clientRetentionStrategy", question: "What strategies do you use to retain clients?" },
        { key: "sustainabilityInvestments", question: "How much do you invest in sustainability initiatives?" },
        { key: "brandAwarenessCampaign", question: "Describe your brand awareness campaign." },
        { key: "socialMediaInfluence", question: "How influential are your social media channels?" },
        { key: "digitalEngagement", question: "How engaged are your users in digital channels?" },
        { key: "productInnovationIndex", question: "How innovative is your product line?" },
        { key: "marketGrowthProjection", question: "What is your projected market growth?" },
        { key: "profitGrowthProjection", question: "What is your projected profit growth?" },
        { key: "investmentReturn", question: "How would you describe your return on investment?" },
        { key: "customerAcquisitionTime", question: "How long does it take to acquire a new customer?" },
        { key: "salesCycleDuration", question: "What is the typical duration of your sales cycle?" },
        { key: "leadTime", question: "What is your average lead time from inquiry to sale?" },
        { key: "contractRenewalRate", question: "What is your contract renewal rate?" },
        { key: "customerEscalationRate", question: "How often do customer issues escalate?" },
        { key: "supportSatisfactionRating", question: "How satisfied are customers with support?" },
        { key: "netRevenueRetention", question: "What is your net revenue retention rate?" },
        { key: "grossMargin", question: "What is your gross margin percentage?" },
        { key: "operatingMargin", question: "What is your operating margin percentage?" },
        { key: "earningsBeforeTax", question: "What are your earnings before tax?" },
        { key: "researchGrants", question: "Do you receive research grants?" },
        { key: "patentFilingRate", question: "How often do you file for patents?" },
        { key: "competitiveBenchmarking", question: "How do you benchmark against competitors?" },
        { key: "marketRiskAssessment", question: "How do you assess market risk?" },
        { key: "supplyChainReliability", question: "How reliable is your supply chain?" },
        { key: "vendorDiversity", question: "How diverse are your vendors?" },
        { key: "resourceUtilization", question: "How efficiently do you utilize resources?" },
        { key: "energyConsumption", question: "What is your energy consumption like?" },
        { key: "wasteManagement", question: "How do you manage waste in your operations?" },
        { key: "carbonFootprint", question: "What is your company's carbon footprint?" },
        { key: "waterUsage", question: "How much water does your operation use?" },
        { key: "greenInitiatives", question: "What green initiatives are you undertaking?" },
        { key: "sustainableSourcing", question: "Do you practice sustainable sourcing?" },
        { key: "ecoFriendlyProducts", question: "Do you offer eco-friendly products?" },
        { key: "corporateEthics", question: "How would you describe your corporate ethics?" },
        { key: "customerDataPrivacy", question: "How do you protect customer data privacy?" },
        { key: "informationSecurityPolicy", question: "What is your information security policy?" },
        { key: "complianceTraining", question: "Do you provide compliance training for employees?" },
        { key: "vendorRiskManagement", question: "How do you manage vendor risk?" },
        { key: "contractualObligations", question: "What are your key contractual obligations?" },
        { key: "clientOnboardingTime", question: "How long does it take to onboard a new client?" },
        { key: "serviceLevelAgreement", question: "What are the terms of your service level agreements?" },
        { key: "operationalEfficiencyRating", question: "How do you rate your operational efficiency?" },
        { key: "processImprovement", question: "What steps do you take to improve processes?" },
        { key: "digitalTransformationIndex", question: "What is your digital transformation index?" },
        { key: "cloudAdoptionLevel", question: "How extensively do you use cloud technology?" },
        { key: "aiIntegrationLevel", question: "To what extent have you integrated AI into your operations?" },
        { key: "automationImpact", question: "What impact has automation had on your processes?" },
        { key: "itCostManagement", question: "How do you manage IT costs?" },
        { key: "softwareLicensing", question: "How do you handle software licensing?" },
        { key: "customerDataAnalyticsUsage", question: "How do you use customer data analytics?" },
        { key: "marketingAutomationUsage", question: "Do you use marketing automation tools?" },
        { key: "leadScoringEffectiveness", question: "How effective is your lead scoring system?" },
        { key: "salesForecastAccuracy", question: "How accurate are your sales forecasts?" },
        { key: "inventoryAccuracyRate", question: "What is your inventory accuracy rate?" },
        { key: "supplyChainVisibility", question: "How visible is your supply chain?" },
        { key: "logisticsEfficiencyRating", question: "How efficient is your logistics network?" },
        { key: "distributionCostEfficiency", question: "How cost-effective is your distribution network?" },
        { key: "customerAcquisitionCostOptimization", question: "How do you optimize customer acquisition costs?" },
        { key: "brandEquityScore", question: "What is your brand equity score?" },
        { key: "socialResponsibilityScoreExtra", question: "How do you measure your social responsibility?" },
        { key: "communityEngagementIndexExtra", question: "What is your community engagement index?" },
        { key: "employeeWellnessProgramEffectiveness", question: "How effective are your employee wellness programs?" },
        { key: "workforceProductivityIndex", question: "What is your workforce productivity index?" },
        { key: "corporateCultureIndex", question: "How would you rate your corporate culture?" },
        { key: "innovationPipelineSpeed", question: "How fast is your innovation pipeline?" },
        { key: "newProductLaunchFrequency", question: "How frequently do you launch new products?" },
        { key: "marketSaturationLevel", question: "What is the saturation level of your market?" },
        { key: "customerServiceTrainingEffectiveness", question: "How effective is your customer service training?" },
        { key: "userExperienceDesignQuality", question: "How would you rate your user experience design quality?" },
        { key: "uxUsabilityTestingResults", question: "What do your usability tests reveal about UX?" },
        { key: "uiConsistencyScore", question: "How consistent is your UI across platforms?" },
        { key: "mobileAppUsabilityScore", question: "How usable is your mobile app?" },
        { key: "websiteConversionRateImprovement", question: "Have you improved your website conversion rate?" },
        { key: "trafficSourcesDiversity", question: "How diverse are your website traffic sources?" },
        { key: "bounceRateImprovement", question: "Have you improved your website bounce rate?" },
        { key: "averageSessionDuration", question: "What is the average session duration on your website?" },
        { key: "pageViewsPerSession", question: "What is the average number of page views per session?" },
        { key: "returnVisitorRate", question: "What percentage of your visitors are returning?" },
        { key: "customerReferralRate", question: "What is your customer referral rate?" },
        { key: "wordOfMouthEffectiveness", question: "How effective is word-of-mouth marketing for you?" },
        { key: "customerAdvocacyLevel", question: "How strong is customer advocacy for your brand?" },
        { key: "netPromoterScoreImprovement", question: "Have you seen improvements in your Net Promoter Score?" },
        { key: "feedbackLoopEfficiency", question: "How efficient is your feedback loop?" },
        { key: "productIterationSpeed", question: "How quickly do you iterate on your products?" },
        { key: "featureAdoptionRate", question: "What is your rate of new feature adoption?" },
        { key: "subscriptionGrowthRate", question: "How fast is your subscription base growing?" },
        { key: "revenuePerUser", question: "What is your revenue per user?" },
        { key: "churnRateReduction", question: "Have you reduced your customer churn rate?" },
        { key: "profitabilityAnalysisMethod", question: "How do you analyze your profitability?" },
        { key: "marketDiversificationStrategy", question: "What is your strategy for market diversification?" },
        { key: "globalExpansionPlanDetails", question: "Describe your global expansion plans." },
        { key: "regionalMarketAnalysis", question: "What does your regional market analysis reveal?" },
        { key: "economicForecastAccuracy", question: "How accurate are your economic forecasts?" },
        { key: "currencyRiskManagementStrategy", question: "How do you manage currency risk?" },
        { key: "tradeTariffsImpact", question: "How do trade tariffs impact your business?" },
        { key: "importExportComplianceProcess", question: "Describe your import/export compliance process." },
        { key: "internationalBusinessStrategy", question: "What is your international business strategy?" },
        { key: "crossBorderInvestmentOpportunities", question: "Do you pursue cross-border investment opportunities?" },
        { key: "jointVentureOpportunities", question: "Do you explore joint venture opportunities?" },
        { key: "mergerIntegrationProcess", question: "How do you integrate mergers?" },
        { key: "acquisitionSynergiesAchieved", question: "Have you achieved synergies from acquisitions?" },
        { key: "financialLeverageRatio", question: "What is your financial leverage ratio?" },
        { key: "debtEquityRatioValue", question: "What is your debt-to-equity ratio?" },
        { key: "capitalExpenditurePlan", question: "Describe your capital expenditure plan." },
        { key: "operatingCashFlowDetails", question: "What are your operating cash flow details?" },
        { key: "freeCashFlowStatus", question: "What is your free cash flow status?" },
        { key: "dividendPayoutPolicy", question: "What is your dividend payout policy?" },
        { key: "sharePricePerformanceHistory", question: "How has your share price performed historically?" },
        { key: "investorRelationsStrategy", question: "What is your investor relations strategy?" },
        { key: "annualGeneralMeetingFrequency", question: "How often do you hold an annual general meeting?" },
        { key: "shareholderCommunicationMethods", question: "How do you communicate with your shareholders?" },
        { key: "financialTransparencyRating", question: "How transparent is your financial reporting?" },
        { key: "marketVolatilityImpact", question: "How does market volatility affect your business?" },
        { key: "hedgingStrategiesUsed", question: "What hedging strategies do you use?" },
        { key: "corporateRebrandingEfforts", question: "Have you undergone any corporate rebranding efforts?" },
        { key: "customerSegmentationMethod", question: "How do you segment your customers?" },
        { key: "targetedAdvertisingEffectiveness", question: "How effective is your targeted advertising?" },
        { key: "contentDistributionChannels", question: "What channels do you use for content distribution?" },
        { key: "inboundMarketingSuccess", question: "How successful is your inbound marketing?" },
        { key: "outboundMarketingStrategies", question: "What outbound marketing strategies do you employ?" },
        { key: "salesIncentivesProgram", question: "Describe your sales incentives program." },
        { key: "marketPositioningStatement", question: "What is your market positioning statement?" },
        { key: "competitivePricingStrategy", question: "What is your competitive pricing strategy?" },
        { key: "distributionChannelsOverview", question: "How do you manage your distribution channels?" },
        { key: "productBundlingOptions", question: "What product bundling options do you offer?" },
        { key: "upsellingTechniques", question: "Describe your upselling techniques." },
        { key: "crossSellingStrategies", question: "What cross-selling strategies do you use?" },
        { key: "customerWinBackCampaign", question: "Do you run customer win-back campaigns?" },
        { key: "brandRevitalizationPlan", question: "What is your brand revitalization plan?" },
        { key: "onlineReputationManagement", question: "How do you manage your online reputation?" },
        { key: "crisisManagementPlan", question: "Do you have a crisis management plan?" },
        { key: "mediaRelationsStrategy", question: "What is your media relations strategy?" },
        { key: "sponsorshipActivationsDetail", question: "Describe your sponsorship activations." },
        { key: "influencerCampaignResults", question: "What results have you seen from influencer campaigns?" },
        { key: "affiliateSalesProgram", question: "Do you have an affiliate sales program?" },
        { key: "loyaltyProgramDetails", question: "What details can you share about your loyalty program?" },
        { key: "promotionalCampaignOverview", question: "Describe your promotional campaigns." },
        { key: "seasonalOfferStrategy", question: "What seasonal offers do you run?" },
        { key: "bulkDiscountStructure", question: "What is your bulk discount structure?" },
        { key: "membershipBenefitsDetail", question: "Describe the benefits of membership." },
        { key: "subscriptionOptionsAvailable", question: "What subscription options are available?" },
        { key: "renewalReminderProcess", question: "How do you handle renewal reminders?" },
        { key: "upgradeOptionDetails", question: "What upgrade options do you offer?" },
        { key: "downgradePolicyDetails", question: "What is your downgrade policy?" },
        { key: "cancellationFeePolicy", question: "Are there any cancellation fees?" },
        { key: "refundProcessDetails", question: "Describe your refund process." },
        { key: "trialConversionRateData", question: "What is your trial conversion rate?" },
        { key: "userChurnRateData", question: "What is your user churn rate?" },
        { key: "customerFeedbackAverage", question: "What is your average customer feedback score?" },
        { key: "socialMediaEngagementMetrics", question: "How do you measure social media engagement?" },
        { key: "websiteTrafficAnalysis", question: "Describe your website traffic analysis." },
        { key: "conversionOptimizationTechniques", question: "What techniques do you use for conversion optimization?" },
        { key: "mobileOptimizationStatus", question: "Is your website optimized for mobile?" },
        { key: "userRetentionStrategies", question: "What strategies do you use for user retention?" },
        { key: "appStoreRatingData", question: "What are your app store ratings?" },
        { key: "featureUsageStats", question: "What are your key feature usage statistics?" },
        { key: "supportSatisfactionData", question: "What is your support satisfaction rating?" },
        { key: "technicalIssueResolutionTime", question: "What is your average technical issue resolution time?" },
        { key: "productReturnRateData", question: "What is your product return rate?" },
        { key: "inventoryTurnoverRateData", question: "What is your inventory turnover rate?" },
        { key: "profitMarginData", question: "What are your profit margins?" },
        { key: "costOfGoodsSoldData", question: "What is your cost of goods sold?" },
        { key: "operationalCostData", question: "What are your operational costs?" },
        { key: "revenueGrowthRateData", question: "What is your revenue growth rate?" },
        { key: "marketForecastProjection", question: "What is your market forecast for the next year?" }
    ];

    await Promise.all(
        questionMappings.map((mapping) =>
            prisma.questionMapping.upsert({
                where: { key: mapping.key },
                update: {},
                create: mapping,
            })
        )
    );
    console.log("Seeded 100 question mappings successfully.");
}

seed()
    .catch((e) =>
    {
        console.error("Error seeding question mappings:", e);
        process.exit(1);
    })
    .finally(async () =>
    {
        await prisma.$disconnect();
    });
